version: '3.8'

services:
  movies:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/ # mounts app code to container. Updates container when code change is made, without rebuilding image.
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev